---
- name: This is my NTP Playbook
  hosts: localhost
  remote_user: jenkins
  become: True
  become_method: sudo
  become_user: root
  

  tasks:
  -  name: Installing NTP Package
     yum: name=ntp state=present

  -  name: Creating file
     file: path=/etc/ntp.conf state=file

  -  name: Starting and Enabling Service Across reboots
     service: name=ntpd state=started enabled=yes
